### ISSUE TITLE
Feature request: populate the gracenote id when importing a playlist

### ISSUE THREAD

**Issue by SethL** [babsonnexus/stream-link-manager-for-channels#20]
Populate the gracenote id when importing a playlist. It's easy to override the gracenote id but you have to look at the m3u to see what it was from the original.  If the original gracenote id was imported I would look at it and change it if necessary

**Comment by babsonnexus** [comment]
The original Gracenote ID is imported already, you can see it in ```Files``` -> ```All Stations```:

![image](https://github.com/user-attachments/assets/52b727b6-d46c-442a-bebc-d62c9abe5219)

The Gracenote ID override is at the parent level and it doesn't know if any of the children have a Gracenote ID until it builds the m3u(s). Since m3u(s) are build dynamically, there is no logical way to do what you are asking. However, I am considering a `Report` to see a parent with all its children and some key info. If I put Gracenote ID in there, it would basically do what you are asking for.
